Numpy Practice Questions
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```


In [ ]:
# Numpy 

In [7]:
# 1) 
import numpy as np
A = np.array([1,2,3,4,5,6,7,8])
B = np.array([6,7,8,9,10,11,12,13])
V = np.vstack((A,B))
H = np.hstack((A,B))
A,B,V,H

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13]),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 6,  7,  8,  9, 10, 11, 12, 13]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  6,  7,  8,  9, 10, 11, 12, 13]))

In [9]:
# 2)
common_ele = np.intersect1d(A,B)
common_ele 

array([6, 7, 8])

In [14]:
# 3)
extraced_ele = A[(A>=5)&(A<=10)]
extraced_ele 

array([5, 6, 7, 8])

In [16]:
# 4)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered = iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)]
filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
# Pandas

In [18]:
# 1)
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
dffiltered = df.iloc[::20][['Manufacturer', 'Model', 'Type' ]]
dffiltered

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [19]:
# 2)
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'].fillna(df['Min.Price'].mean(),inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(),inplace=True)
df[['Min.Price','Max.Price']]

Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

In [20]:
# 3)
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtereddf = df[df.sum(axis=1)>100]
filtereddf

0   1   2   3
0   28  37  29  17
2   35  38  22  18
3   38  23  39  22
4   37  31  36  14
8   28  29  31  38
10  30  39  29  12
11  29  19  18  37
13  35  11  39  19
14  27  38  29  31